version: '3.3'

services:
  # React frontend
  front:
    container_name: front
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - VITE_API_TARGET=${VITE_API_TARGET}
    ports:
      - 80:80